### ISSUE TITLE
Error: Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by KirillioClockwork** [utazabanje/js-cookie-consent#2]
When I use 'js-cookie-consent' with Next.js I have this error when compiling: 
![image](https://user-images.githubusercontent.com/72017958/116892915-0ca22b80-ac39-11eb-9846-1a55bf904d78.png)
https://err.sh/next.js/css-npm
I think problem is this ('/node_modules/js-cookie-consent/dist/index.js'):
![image](https://user-images.githubusercontent.com/72017958/116893159-53902100-ac39-11eb-8941-e25aad64aed0.png)

Can you fix it? @utazabanje

**Comment by utazabanje** [comment]
@KirillioClockwork  should be fixed after the latest release.
